In [1]:
import sys
sys.path.append('../')
from unit.config import config
from unit.dataset_multiclass import get_dataloaders
from unit.model import ContrastiveLearningModel
import torch
from tqdm.auto import tqdm

In [2]:
train_loader, val_loader  = get_dataloaders(config.BATCH_SIZE,
                                            config.NUM_WORKERS, 
                                            config.MAX_LENGTH,
                                            dataset_path_or_name='imdb')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


Conver to Embeddings:   0%|          | 0/25000 [00:00<?, ?it/s]

In [7]:
for i, data in enumerate(train_loader):
    print(f'{i+1}. pair of contrastive')
    input_ids, mask, label = data
    print(input_ids.squeeze().size())
    print(input_ids.squeeze()[:,:10])
    print(mask.squeeze().size())
    print(mask.squeeze()[:,:10])
    print(label.squeeze().size())
    print(label.squeeze())
    print('end')
    if i >= 0:
        break

/ |#                                                  | 0 Elapsed Time: 0:00:00
- | #                                                | 19 Elapsed Time: 0:00:00


1. pair of contrastive
torch.Size([4, 128])
tensor([[  101,  1045,  4384,  2012,  2320,  2008,  2023,  3185,  2428,  2347],
        [  101,  5064,  1010,  2023,  3185,  9020,  2000,  2022,  1999,  5737],
        [  101,  1996,  3819,  4028,  2003, 17910,  2098,  2043,  1037,  2564],
        [  101,  2748,  1010,  1045,  2113,  1045,  1005,  1049,  2028,  1997]])
torch.Size([4, 128])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
torch.Size([4])
tensor([1, 1, 0, 0])
end


In [6]:
for i, data in enumerate(val_loader):
    print(f'{i+1}. pair of contrastive')
    input_ids, mask, label = data
    print(input_ids.squeeze().size())
    print(input_ids.squeeze()[:10])
    print(mask.squeeze().size())
    print(mask.squeeze()[:10])
    print(label.squeeze().size())
    print(label.squeeze())
    print('end')
    if i >= 0:
        break

1. pair of contrastive
torch.Size([4, 128])
tensor([[  101,  1045,  2293, 16596,  1011, 10882,  1998,  2572,  5627,  2000,
          2404,  2039,  2007,  1037,  2843,  1012, 16596,  1011, 10882,  5691,
          1013,  2694,  2024,  2788,  2104, 11263, 25848,  1010,  2104,  1011,
         12315,  1998, 28947,  1012,  1045,  2699,  2000,  2066,  2023,  1010,
          1045,  2428,  2106,  1010,  2021,  2009,  2003,  2000,  2204,  2694,
         16596,  1011, 10882,  2004, 17690,  1019,  2003,  2000,  2732, 10313,
          1006,  1996,  2434,  1007,  1012, 10021,  4013,  3367, 20086,  2015,
          1010, 10036, 19747,  4520,  1010, 25931,  3064, 22580,  1010,  1039,
          2290,  2008,  2987,  1005,  1056,  2674,  1996,  4281,  1010,  1998,
         16267,  2028,  1011,  8789,  3494,  3685,  2022,  9462,  2007,  1037,
          1005, 16596,  1011, 10882,  1005,  4292,  1012,  1006,  1045,  1005,
          1049,  2469,  2045,  2024,  2216,  1997,  2017,  2041,  2045,  2040,
        

In [9]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

# 加载最佳模型检查点
model = ContrastiveLearningModel(model_name=config.MODEL_NAME)

# 进行推理和评估
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()
for i, batch in enumerate(tqdm(train_loader)):
    input_ids, attention_mask, label = [t.squeeze().to(device) for t in batch]
    output = model(input_ids=input_ids, attention_mask=attention_mask)
    print(output)
    print(label)
    loss = torch.nn.functional.cross_entropy(output,label)
    print(loss)
    '''
    pred = torch.argmax(output, dim=1)
    val_preds = pred.cpu()
    val_labels = label.cpu()
    precision = precision_score(val_labels, val_preds, average='micro')
    recall = recall_score(val_labels, val_preds, average='micro')
    f1 = f1_score(val_labels, val_preds, average='micro')
    accuracy = accuracy_score(val_labels, val_preds)

    print('val_precision', precision)
    print('val_recall', recall)
    print('val_f1', f1)
    print('val_accuracy', accuracy)
    '''
    

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
/ |#                                                  | 0 Elapsed Time: 0:00:00


  0%|          | 0/6250 [00:00<?, ?it/s]

/ |#                                                  | 0 Elapsed Time: 0:00:00
- | #                                                | 20 Elapsed Time: 0:00:00
\ |  #                                               | 25 Elapsed Time: 0:00:00


tensor([[ 0.0088, -0.1258],
        [-0.1019, -0.1434],
        [ 0.1229, -0.2430],
        [ 0.0328,  0.0125]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7242, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1608, -0.2034],
        [-0.0213,  0.0165],
        [ 0.2387,  0.0291],
        [ 0.1231, -0.0625]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7084, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-1.0900e-01, -2.0336e-01],
        [ 4.8706e-02, -1.7089e-02],
        [-5.7105e-05, -2.3141e-01],
        [-1.1662e-01,  2.6274e-01]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6612, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1076, -0.1642],
        [ 0.0751, -0.0298],
        [-0.0769, -0.2263],
        [ 0.0582,  0.0602]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.667

| |   #                                              | 31 Elapsed Time: 0:00:00
/ |    #                                             | 38 Elapsed Time: 0:00:00


tensor([[ 0.0373, -0.3312],
        [-0.0133, -0.1254],
        [-0.0854, -0.2331],
        [ 0.1365, -0.1071]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6891, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.0243,  0.0094],
        [-0.0765, -0.1042],
        [ 0.1357, -0.0343],
        [ 0.0178, -0.2212]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7478, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1462, -0.1478],
        [-0.1179, -0.4021],
        [-0.1580,  0.0294],
        [ 0.0380, -0.2000]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7672, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.2283, -0.3274],
        [-0.1123,  0.0507],
        [-0.0394, -0.0296],
        [-0.1492, -0.3911]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7254, device='cuda:0', grad_fn=<Nll

- |     #                                            | 44 Elapsed Time: 0:00:00
\ |      #                                           | 50 Elapsed Time: 0:00:00


tensor([[ 0.1168, -0.0658],
        [ 0.1266, -0.1389],
        [ 0.3482,  0.0443],
        [-0.0546, -0.1603]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7044, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.0105, -0.4426],
        [ 0.1179, -0.2017],
        [ 0.0097,  0.0085],
        [-0.0511, -0.0033]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6024, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.0576, -0.3014],
        [ 0.0087,  0.1437],
        [ 0.2208, -0.2452],
        [-0.1920, -0.0799]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7211, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.3749, -0.1218],
        [ 0.0832, -0.4684],
        [ 0.0586, -0.2173],
        [-0.0207, -0.0666]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.8034, device='cuda:0', grad_fn=<Nll

| |       #                                          | 56 Elapsed Time: 0:00:00
/ |        #                                         | 62 Elapsed Time: 0:00:00


tensor([[-0.0827, -0.0990],
        [-0.0912, -0.1544],
        [-0.0547, -0.3322],
        [ 0.0859, -0.1605]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.6420, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1055, -0.1960],
        [-0.0729, -0.1360],
        [ 0.0299, -0.1341],
        [ 0.1930, -0.0415]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7029, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.2558, -0.0950],
        [ 0.1059, -0.0866],
        [-0.2117,  0.0097],
        [-0.0342, -0.2475]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7700, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1458, -0.1865],
        [ 0.0650, -0.2731],
        [ 0.3736,  0.2580],
        [ 0.0866, -0.1007]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6557, device='cuda:0', grad_fn=<Nll

- |         #                                        | 68 Elapsed Time: 0:00:00
\ |          #                                       | 74 Elapsed Time: 0:00:01


tensor([[ 0.0837, -0.1562],
        [-0.0057, -0.4267],
        [-0.0415, -0.0977],
        [-0.1818, -0.1922]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6263, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.1349, -0.4449],
        [-0.1282, -0.1696],
        [ 0.0711, -0.1420],
        [-0.1130, -0.0286]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6700, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.0911, -0.2001],
        [ 0.2817, -0.1125],
        [-0.1083, -0.0040],
        [ 0.0743, -0.1560]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6532, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.0844, -0.0646],
        [-0.0835,  0.0471],
        [-0.0948, -0.1408],
        [ 0.2483,  0.0143]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.6417, device='cuda:0', grad_fn=<Nll

| |           #                                      | 80 Elapsed Time: 0:00:01
/ |            #                                     | 86 Elapsed Time: 0:00:01


tensor([[-0.0349, -0.2162],
        [-0.0134, -0.4468],
        [ 0.0755, -0.2106],
        [-0.0930, -0.2501]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7247, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.0587, -0.3069],
        [ 0.0136,  0.0540],
        [-0.2122, -0.0664],
        [ 0.0205, -0.3442]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7013, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.0891,  0.0408],
        [ 0.3025,  0.3267],
        [ 0.0773, -0.1076],
        [ 0.0903, -0.1045]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7399, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1531, -0.2016],
        [-0.0421, -0.0897],
        [ 0.0287,  0.0147],
        [-0.0232, -0.0911]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6572, device='cuda:0', grad_fn=<Nll

- |             #                                    | 92 Elapsed Time: 0:00:01
\ |              #                                   | 98 Elapsed Time: 0:00:01


tensor([[ 0.0173, -0.0092],
        [-0.2318, -0.0232],
        [-0.0007,  0.0133],
        [-0.0876,  0.0580]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6980, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1720,  0.0998],
        [ 0.1233, -0.1884],
        [-0.0074, -0.1082],
        [-0.0407,  0.0730]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7467, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1773, -0.3191],
        [ 0.1117, -0.2301],
        [-0.0172, -0.3117],
        [ 0.1065, -0.1808]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7417, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.0024, -0.0484],
        [-0.0608, -0.2856],
        [ 0.0316,  0.1195],
        [-0.1319, -0.0668]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6422, device='cuda:0', grad_fn=<Nll

| |               #                                 | 104 Elapsed Time: 0:00:01
/ |                #                                | 110 Elapsed Time: 0:00:01


tensor([[ 0.2873, -0.3260],
        [ 0.1250,  0.3054],
        [ 0.1980, -0.0582],
        [-0.0090, -0.0717]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6937, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1280, -0.3536],
        [-0.0191, -0.3440],
        [ 0.0783, -0.1290],
        [ 0.0290, -0.1983]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7530, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1713, -0.0174],
        [ 0.1586, -0.0170],
        [-0.0544, -0.1224],
        [-0.0906,  0.1404]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6311, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.1118,  0.0630],
        [ 0.0612, -0.2521],
        [ 0.0136,  0.0224],
        [ 0.3605,  0.0401]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.6787, device='cuda:0', grad_fn=<Nll

- |                 #                               | 116 Elapsed Time: 0:00:01
\ |                  #                              | 122 Elapsed Time: 0:00:01


tensor([[-0.1296, -0.1564],
        [ 0.0840,  0.0471],
        [-0.1275,  0.1405],
        [-0.0492, -0.2031]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6740, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.0268, -0.2120],
        [ 0.2346, -0.0407],
        [ 0.0115, -0.1720],
        [ 0.1952, -0.0568]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7101, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1477, -0.4337],
        [ 0.1608,  0.1077],
        [ 0.0032, -0.3190],
        [ 0.1596,  0.0734]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7354, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.0273, -0.1475],
        [-0.0506, -0.0537],
        [ 0.0943, -0.0441],
        [ 0.1401, -0.1484]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7284, device='cuda:0', grad_fn=<Nll

| |                   #                             | 128 Elapsed Time: 0:00:01
/ |                    #                            | 134 Elapsed Time: 0:00:02


tensor([[ 0.0427,  0.0561],
        [-0.2602, -0.1046],
        [ 0.1040, -0.1286],
        [ 0.1274, -0.0330]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7666, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1770, -0.2424],
        [ 0.1553, -0.1453],
        [ 0.0956, -0.0019],
        [ 0.1019, -0.1293]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6545, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.0490, -0.1579],
        [ 0.1193, -0.2110],
        [ 0.1300, -0.0043],
        [ 0.0241, -0.0359]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7282, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1173, -0.2904],
        [ 0.1094, -0.0482],
        [ 0.1696, -0.1320],
        [ 0.3758,  0.2568]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7204, device='cuda:0', grad_fn=<Nll

- |                     #                           | 140 Elapsed Time: 0:00:02
\ |                      #                          | 146 Elapsed Time: 0:00:02


tensor([[-0.0164, -0.2176],
        [-0.2525, -0.1048],
        [ 0.1174, -0.0762],
        [ 0.1088, -0.0261]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7312, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.0991, -0.1140],
        [ 0.2457, -0.3058],
        [ 0.1596, -0.1159],
        [-0.0107, -0.2472]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7396, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.0786, -0.1083],
        [ 0.0701, -0.0371],
        [ 0.1875,  0.0177],
        [ 0.1614, -0.2057]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.6486, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.0100, -0.1140],
        [ 0.1759, -0.0131],
        [ 0.0487, -0.0171],
        [ 0.0255, -0.1649]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7005, device='cuda:0', grad_fn=<Nll

| |                       #                         | 152 Elapsed Time: 0:00:02
/ |                        #                        | 158 Elapsed Time: 0:00:02


tensor([[-0.0217, -0.3026],
        [ 0.0483, -0.1300],
        [ 0.0296, -0.1013],
        [ 0.0803, -0.0682]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6753, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.2560, -0.0914],
        [-0.0041,  0.0123],
        [ 0.1052, -0.2322],
        [-0.0680, -0.0026]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.6410, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1283,  0.1828],
        [ 0.0273,  0.0747],
        [ 0.2288, -0.2117],
        [ 0.0017,  0.0709]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.6403, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.0891, -0.1774],
        [ 0.1181, -0.4283],
        [-0.0851, -0.0204],
        [ 0.1859, -0.0706]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7844, device='cuda:0', grad_fn=<Nll

- |                         #                       | 164 Elapsed Time: 0:00:02
\ |                           #                     | 170 Elapsed Time: 0:00:02


tensor([[ 0.0925, -0.0484],
        [ 0.1172, -0.2793],
        [ 0.1034, -0.1441],
        [-0.0431,  0.0852]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6488, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1941, -0.1178],
        [-0.0728, -0.3562],
        [-0.1660, -0.3855],
        [ 0.1804,  0.0826]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6657, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1066, -0.3028],
        [ 0.1320, -0.2094],
        [ 0.2466,  0.3388],
        [ 0.2192, -0.2880]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6682, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[-0.1423,  0.0083],
        [ 0.0425, -0.2610],
        [-0.0986, -0.2032],
        [ 0.0353, -0.2353]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.6716, device='cuda:0', grad_fn=<Nll

| |                            #                    | 176 Elapsed Time: 0:00:02
/ |                             #                   | 182 Elapsed Time: 0:00:02


tensor([[-0.1170, -0.1331],
        [ 0.0305,  0.1134],
        [ 0.0951,  0.1754],
        [-0.0202, -0.1046]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.7027, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1087, -0.2300],
        [ 0.0353, -0.2499],
        [ 0.0278, -0.1014],
        [ 0.2850, -0.1396]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([1, 1, 0, 0], device='cuda:0')
tensor(0.7141, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.1285,  0.0460],
        [ 0.2358,  0.0134],
        [-0.1887, -0.1046],
        [ 0.2155, -0.0650]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6840, device='cuda:0', grad_fn=<NllLossBackward0>)
tensor([[ 0.0320, -0.1925],
        [ 0.0616, -0.0064],
        [ 0.0843, -0.1988],
        [-0.2794, -0.2928]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0, 0, 1, 1], device='cuda:0')
tensor(0.6979, device='cuda:0', grad_fn=<Nll

KeyboardInterrupt: 

In [8]:
import numpy as np

# 建立一個形狀為 2x4x128 的矩陣
matrix = np.random.rand(2, 4, 5)

# 獲取矩陣的形狀
shape = matrix.shape

# 計算前兩個維度的乘積
new_shape_first_dim = shape[0] * shape[1]

# 自動設置新的形狀
reshaped_matrix = matrix.reshape(new_shape_first_dim, shape[2])

print("原始矩陣形狀:", matrix.shape)
print("降維後的矩陣形狀:", reshaped_matrix.shape)


原始矩陣形狀: (2, 4, 5)
降維後的矩陣形狀: (8, 5)


In [9]:
matrix

array([[[0.79557872, 0.46039835, 0.56563753, 0.7488221 , 0.46439358],
        [0.7928888 , 0.96784006, 0.08237206, 0.02275389, 0.1669453 ],
        [0.15931366, 0.47206555, 0.57146352, 0.1049263 , 0.31776827],
        [0.36920129, 0.80437327, 0.14996319, 0.16418124, 0.94332088]],

       [[0.31249487, 0.88598467, 0.34534662, 0.46421781, 0.0354572 ],
        [0.0720262 , 0.80569732, 0.10087847, 0.70427672, 0.43372558],
        [0.75418592, 0.34902049, 0.03212869, 0.58542441, 0.61343425],
        [0.86287771, 0.46624563, 0.26669618, 0.88591575, 0.13587397]]])

In [10]:
reshaped_matrix

array([[0.79557872, 0.46039835, 0.56563753, 0.7488221 , 0.46439358],
       [0.7928888 , 0.96784006, 0.08237206, 0.02275389, 0.1669453 ],
       [0.15931366, 0.47206555, 0.57146352, 0.1049263 , 0.31776827],
       [0.36920129, 0.80437327, 0.14996319, 0.16418124, 0.94332088],
       [0.31249487, 0.88598467, 0.34534662, 0.46421781, 0.0354572 ],
       [0.0720262 , 0.80569732, 0.10087847, 0.70427672, 0.43372558],
       [0.75418592, 0.34902049, 0.03212869, 0.58542441, 0.61343425],
       [0.86287771, 0.46624563, 0.26669618, 0.88591575, 0.13587397]])